name: Build Windows Exe

# Trigger action whenever you push to the main branch
on:
  push:
    branches: [ "main" ]
  workflow_dispatch: # Allows manual run from the actions tab

jobs:
  build:
    runs-on: windows-latest  # Request Windows computer 

    steps:
    # 1. Check out for Windows 
    - uses: actions/checkout@v4

    # 2. Install Python
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'

    # 3. Install libraries
    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pandas numpy pyinstaller

    # 4. Build Organizer Script
    - name: Build Organizer Exe
      run: pyinstaller --onefile run_nihTB_organization.py

    # 5. Build Verifier Script
    - name: Build Verifier Exe
      run: pyinstaller --onefile run_nihTB_verify.py

    # 6. Upload finished .exe files for download
    - name: Upload Artifacts
      uses: actions/upload-artifact@v4
      with:
        name: Windows-Executables
        path: dist/*.exe
