name: Build Windows Exe

# Trigger action when main branch push
on:
  push:
    branches: [ "main" ]
  workflow_dispatch: # Allows actions tab run

jobs:
  build:
    runs-on: windows-latest  # Get windows os 

    steps:
    # Checkout
    - uses: actions/checkout@v4

    # Install python
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'

    # Install libraries
    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pandas numpy pyinstaller

    # Organizer run script 
    - name: Build Organizer Exe
      run: pyinstaller --onefile run_nihTB_organization.py

    # Verifier run script 
    - name: Build Verifier Exe
      run: pyinstaller --onefile run_nihTB_verify.py
    
    # NDA Formatting run script
    - name: Build NDA Formatting Exe
      run: pyinstaller --onefile run_nihTB_ndaformat.py

    # Upload finished .exe files for download
    - name: Upload Artifacts
      uses: actions/upload-artifact@v4
      with:
        name: Windows-Executables
        path: dist/*.exe
